metricsEndpoints:
  - indexer:
      type: local
global:
  measurements:
  - name: vmiLatency

jobs:

  - name: dv-source
    jobType: create
    jobIterations: {{.ITERATIONS}}
    namespacedIterations: true
    namespace: vm-simple
    qps: {{.QPS}}
    burst: {{.BURST}}
    maxWaitTimeout: 2m
    jobPause: 2m
    objects:

    - objectTemplate: templates/dv-source.yml
      replicas: 1
      inputVars:
        url: https://dl.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
        storage: 10Gi
        storageclass: powermax-fc
        volumemode: Block

    - objectTemplate: templates/dv-volsnap.yml
      replicas: 1
      inputVars:
        volsnapclass: powermax-snapclass

