metricsEndpoints:
  - endpoint: {{ .PROM }}
    token: {{.PROM_TOKEN}}
    indexer:
      type: local
  - indexer:
      type: local
      metricsDirectory: /var/tmp/kube-burner

global:
  measurements:
  - name: podLatency

jobs:
  - name: statefulset-churn
    jobIterations: {{.ITERATIONS}}
    namespacedIterations: true
    namespace: pvc-churning
    qps: {{.QPS}}
    burst: {{.BURST}}
    churn: true
    churnPercent: 20
    churnDuration: 1h
    churnDelay: 0s
    objects:
      - objectTemplate: templates/sts.yaml
        replicas: {{.OBJ_REPLICAS}}
        inputVars:
          storageClass: powerstore
