apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio-sleep-{{.Iteration}}-{{.Replica}}
spec:
  serviceName: fio-sleep-{{.Iteration}}-{{.Replica}}
  replicas: 1
  selector:
    matchLabels:
      app: fio-sleep-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: fio-sleep-{{.Iteration}}-{{.Replica}}
    spec:
{{- if .nodename }}
      nodeName: {{.nodename}}
{{- end }}
      containers:
      - name: test
        image: ghcr.io/coulof/fio:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep", "3600" ]
        volumeMounts:
        - mountPath: "/data"
          name: pvolx-0
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
  - metadata:
      name: pvolx-0
    spec:
      volumeMode: Filesystem
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClass }}
      resources:
        requests:
          storage: 1Gi

